// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD2XpHlGatqd519fpWOvXIDp70IeoRZ8k',
    appId: '1:1098435280884:web:0bb0b96c078cc95d5a43a1',
    messagingSenderId: '1098435280884',
    projectId: 'staj-servis',
    authDomain: 'staj-servis.firebaseapp.com',
    storageBucket: 'staj-servis.firebasestorage.app',
    measurementId: 'G-1548P705MX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgSUdsblScN4rTqAvX5MQD6hZaBbQxwRg',
    appId: '1:1098435280884:android:9b3279fd40fcc3c75a43a1',
    messagingSenderId: '1098435280884',
    projectId: 'staj-servis',
    storageBucket: 'staj-servis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfmAkKQJ5_sRAMTQzIpqnDxSBnP953V1c',
    appId: '1:1098435280884:ios:4e8c45d3061681155a43a1',
    messagingSenderId: '1098435280884',
    projectId: 'staj-servis',
    storageBucket: 'staj-servis.firebasestorage.app',
    iosBundleId: 'com.example.stajTakipMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCD2XpHlGatqd519fpWOvXIDp70IeoRZ8k',
    appId: '1:1098435280884:web:058487d2712c06f95a43a1',
    messagingSenderId: '1098435280884',
    projectId: 'staj-servis',
    authDomain: 'staj-servis.firebaseapp.com',
    storageBucket: 'staj-servis.firebasestorage.app',
    measurementId: 'G-9DY1RDSGH1',
  );
}
